### ISSUE TITLE
Automatic update is broken

### ISSUE THREAD

**Issue by ghost** [adonais/skylark#61] opened 2023-05-31 11:34 UTC
Help -> About always said there is update available. I did click to restart the application to complete the update but each of the time I go to Help -> About, it always said there is update available! Look at the version number there is nothing changed between updates so I'm pretty sure I'm already having the latest version!

**Comment by adonais** [comment] 2023-07-22 07:43
Maybe it's caused by the time zone issue.
Use your browser to check the timestamp of the latest release, e.g. Release 20230722145808,
And then open the help menu of the skylark editor to check the compile time,
The possible display looks like this "Compiler Info: clang 15.0.7 (2023-07-22 14:51:14)"

**Comment by iahunq** [comment] 2023-07-22 09:53
> Maybe it's caused by the time zone issue. Use your browser to check the timestamp of the latest release, e.g. Release 20230722145808, And then open the help menu of the skylark editor to check the compile time, The possible display looks like this "Compiler Info: clang 15.0.7 (2023-07-22 14:51:14)"

This is what I see: `Compiler Info: clang 15.0.7 (2023-07-22 13:51:14)`.

**Comment by adonais** [comment] 2023-07-22 10:30
Confirmed to be a time zone issue, will be fixed in a later release.

**Closed** 2023-07-28 06:21 UTC
